### ISSUE TITLE
Push message callback fired twice on iOS if app has been killed

### ISSUE THREAD

**Issue by heyman** [nativescript-community/nativescript-push#2]
The `onPushTokenReceivedCallback` gets called twice if the app has been killed and a notification is tapped.

Steps to reproduce:

* Add a console.log call in the `onPushTokenReceivedCallback` callback function
* Start the app
* Kill the app
* Trigger a push notification
* Open the app by tapping the notification 
* The callback will be called twice (the console log will contain two entries)

I assume that the same will happen if the app has been recycled out by the OS, but I haven't tested that.

**Comment by farfromrefug** [comment]
@heyman hopefully 1.1.7 should fix this.
Thanks for the detailed report!

**Comment by kajic** [comment]
I just confirmed that this doesn't happen in 1.1.7.

**Comment by heyman** [comment]
I closed it prematurely. 1.1.7 does not seem to have fixed the issue unfortunately.

EDIT: Apparently the `onPushTokenReceivedCallback` does *not* get called twice. However the the `onMessageReceivedCallback` does get called twice when the app has been killed. Not sure if I wrote the wrong description in my initial bug report, or if it's simply another issue with the other callback as well.

**Comment by farfromrefug** [comment]
@heyman could you try 1.1.9 ?

**Comment by kajic** [comment]
~~I don't think this is occurring anymore! I just tested it on both iOS and Android.~~

EDIT: I just saw it again on iOS (after tapping a notification while the app is killed). I still don't think it's occurring on Android.
